name: 'Scan Dependencies'
run-name: Scan Dependencies
on:
  push:
   branches-ignore: [main]
   paths-ignore:
     - .github/**
jobs:
 scan-dependencies:
   runs-on: ubuntu-latest
   env:
     JF_ENV_1: ${{ secrets.JF_ENV_1 }}
     JFROG_BUILD_STATUS: PASS
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Setup JFrog CLI
       uses: jfrog/setup-jfrog-cli@v3
     - name: Set up JDK 17
       uses: actions/setup-java@v2
       with:
         java-version: '17'
         distribution: 'temurin'
     - name: Audit Dependencies
       run: |
         jf audit --mvn